### ISSUE TITLE
ModuleNotFoundError  'meshzoo' on 0.6.5

### ISSUE THREAD

**Issue by fredsavoir** [nschloe/colorio#84]
Hi,

On fresh system the Meshzoo is not installed and not in dependency.

Here the output.

>>> import colorio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/colorio/__init__.py", line 3, in <module>
    from ._cam16 import CAM16, CAM16UCS
  File "/usr/local/lib/python3.9/site-packages/colorio/_cam16.py", line 3, in <module>
    from ._ciecam02 import compute_from, compute_to
  File "/usr/local/lib/python3.9/site-packages/colorio/_ciecam02.py", line 3, in <module>
    from ._color_space import ColorSpace
  File "/usr/local/lib/python3.9/site-packages/colorio/_color_space.py", line 11, in <module>
    from ._tools import get_mono_outline_xy, get_munsell_data, spectrum_to_xyz100
  File "/usr/local/lib/python3.9/site-packages/colorio/_tools.py", line 5, in <module>
    import meshzoo
ModuleNotFoundError: No module named 'meshzoo'

**Comment by nschloe** [comment]
It's an optional dependency. Install with
```
pip install colorio[all]
```
